---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mmyvv/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH